project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    - .nojekyll

website:
  title: "Your Simple Guide"
  site-url: "https://yoursimpleguide.com"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Homeschool
        menu:
          - href: homeschool/index.qmd
            text: Overview
          - href: homeschool/brailee.qmd
            text: Brailee
          - href: homeschool/addy.qmd
            text: Addy
  page-footer:
    center: "yoursimpleguide.com"

format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: false
    link-external-newwindow: true
    link-external-icon: false

editor: source
